### ISSUE TITLE
Compile with gcc 4.6.4 on OSX 10.8

### ISSUE THREAD

**Issue by MBRSL** [deeplearningais/curfil#5]
Hello, I tried to compile this library on my Mac but failed. Would you please tell me the compiler and OS you use to compile these code?

My compiler showed "random_tree.h:157:9: error: 'isnan' was not declared in this scope." I searched over Internet[1] and find out that < cmath > should be paired with std::isnan() rather than isnan(). So I replaced isnan() with std::isnan() but got another error "random_tree.h(157): error: expected an identifier." Simliar errors occurred if I use < math.h > with isnan() instead.

Do you have any suggestions? Thanks.

[1] http://stackoverflow.com/questions/18128899/
